{{- if .Values.autoScale.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:  
    {{- include "common.helm" . | nindent 4 }}  
  namespace: {{ include "microservice.namespace" . }}
  name: {{ include "common.name.value" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.name.value" . }}
  minReplicas: {{ .Values.autoScale.minReplicas }}
  maxReplicas: {{ .Values.autoScale.maxReplicas }}
  metrics:
  {{- toYaml .Values.autoScale.metrics | nindent 4}}
{{- end }} 