{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.helm" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "microservice.namespace" . }}
{{- end }}    