info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}